/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duan1.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author QUAN
 */
public class ChonMonJFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChonMonJFrame
     */
    public ChonMonJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnToan = new javax.swing.JButton();
        btnHoa = new javax.swing.JButton();
        btnLy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnToan.setText("TOÁN");
        btnToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToanActionPerformed(evt);
            }
        });

        btnHoa.setText("HOÁ");
        btnHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaActionPerformed(evt);
            }
        });

        btnLy.setText("LÝ");
        btnLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLyActionPerformed(evt);
            }
        });

        jLabel1.setText("Vui lòng chọn môn:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToanActionPerformed
        // TODO add your handling code here:
        ExamJFrame ef;
        try {
            ef = new ExamJFrame("M01");
            this.getParent().add(ef);
            ef.setVisible(true);
            ef.setLayer(100);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở exam");
        }
    }//GEN-LAST:event_btnToanActionPerformed

    private void btnLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLyActionPerformed
        // TODO add your handling code here:
        ExamJFrame ef;
        try {
            ef = new ExamJFrame("M02");
            this.getParent().add(ef);
            ef.setVisible(true);
            ef.setLayer(100);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở exam");
        }
    }//GEN-LAST:event_btnLyActionPerformed

    private void btnHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaActionPerformed
        // TODO add your handling code here:
        ExamJFrame ef;
        try {
            ef = new ExamJFrame("M03");
            this.getParent().add(ef);
            ef.setVisible(true);
            ef.setLayer(100);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở exam");
        }
    }//GEN-LAST:event_btnHoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoa;
    private javax.swing.JButton btnLy;
    private javax.swing.JButton btnToan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
