/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duan1.ui;

import com.duan1.helper.DialogHelper;
import com.duan1.helper.ShareHelper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class GiaoDienJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PolyExam
     */
    public GiaoDienJFrame() {
        initComponents();
        setTitle("Hệ thống quản lý thi");
        setLocationRelativeTo(null);
        tab.setEnabledAt(1, true);
        ImageIcon icon = new ImageIcon(ShareHelper.APP_ICON);
        setIconImage(ShareHelper.APP_ICON);
        btn(false);
        if(ShareHelper.USER == null){
        btnKetQua.setEnabled(false);
        tab.setEnabled(false);
        tab.setSelectedIndex(1);
        }
        if(ShareHelper.USERGV==null){
        lblMhs.setText(ShareHelper.USER.getId());
        lblTen.setText(ShareHelper.USER.getTen());
        lblMail.setText(ShareHelper.USER.getEmail());
        tab.setEnabled(false);
        mnuQuanLy.setEnabled(false);
        mnuThongKe.setEnabled(false);
        }
        new Timer(1000, new ActionListener() { 
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a"); 
            @Override 
            public void actionPerformed(ActionEvent e) { 
                lblDongHo.setText(format.format(new Date())); 
            } 
        }).start(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnLBTongHop = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnLBTheoMon = new javax.swing.JButton();
        btnLy = new javax.swing.JButton();
        btnToan = new javax.swing.JButton();
        btnHoa = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btnKetQua = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnDangXuat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnThoat = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblMhs = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        hocsinh = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnHocSinh = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnCauHoi = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnDiemTongHop = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnDangXuatGV = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnThoat2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniThoat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniQLiHocSinh = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        mniQLiCauHoi = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        mniQLiGiaoVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniTKNguoiThi = new javax.swing.JMenuItem();
        mniTKBangDiem = new javax.swing.JMenuItem();
        mniTKDiemTongHop = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jDesktopPane2.setEnabled(false);
        jDesktopPane2.setOpaque(false);

        btnLBTongHop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLBTongHop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Database.png"))); // NOI18N
        btnLBTongHop.setText("<html><br/><br/><br/> LÀM BÀI TỔNG HỢP</html>");
        btnLBTongHop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLBTongHop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLBTongHopActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CHỌN PHẦN THI");

        btnLBTheoMon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLBTheoMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/List.png"))); // NOI18N
        btnLBTheoMon.setText("<html><br/><br/><br/> LÀM BÀI THEO MÔN</html>");
        btnLBTheoMon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLBTheoMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLBTheoMonActionPerformed(evt);
            }
        });

        btnLy.setText("LÝ");
        btnLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLyActionPerformed(evt);
            }
        });

        btnToan.setText("TOÁN");
        btnToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToanActionPerformed(evt);
            }
        });

        btnHoa.setText("HOÁ");
        btnHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnLBTheoMon)
                .addGap(116, 116, 116)
                .addComponent(btnLBTongHop)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(145, 145, 145))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnToan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLy, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(btnHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLBTongHop, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLBTheoMon, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLy, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(105, 271));
        jToolBar2.setPreferredSize(new java.awt.Dimension(105, 271));
        jToolBar2.add(jSeparator10);

        btnKetQua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/To do list.png"))); // NOI18N
        btnKetQua.setText("Kết quả thi");
        btnKetQua.setFocusable(false);
        btnKetQua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetQua.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnKetQua.setMinimumSize(new java.awt.Dimension(105, 65));
        btnKetQua.setPreferredSize(new java.awt.Dimension(105, 65));
        btnKetQua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetQuaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnKetQua);
        jToolBar2.add(jSeparator12);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Log out.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnDangXuat.setMinimumSize(new java.awt.Dimension(105, 65));
        btnDangXuat.setPreferredSize(new java.awt.Dimension(105, 65));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar2.add(btnDangXuat);
        jToolBar2.add(jSeparator3);

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Stop.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnThoat.setMinimumSize(new java.awt.Dimension(105, 65));
        btnThoat.setPreferredSize(new java.awt.Dimension(105, 65));
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jToolBar2.add(btnThoat);
        jToolBar2.add(jSeparator16);

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Info.png"))); // NOI18N
        jLabel10.setText("Hệ thống quản lý thi");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Alarm.png"))); // NOI18N

        lblDongHo.setText("Time");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblDongHo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/logo (1).png"))); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("THÔNG TIN HỌC SINH");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Họ tên:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Mã học sinh:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Email:");

        lblMhs.setText("jLabel4");

        lblTen.setText("jLabel5");

        lblMail.setText("jLabel6");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMhs, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lblMail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab.addTab("Học sinh", jPanel1);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRequestFocusEnabled(false);
        jToolBar1.add(jSeparator4);

        btnHocSinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Conference.png"))); // NOI18N
        btnHocSinh.setText("QL Học Sinh");
        btnHocSinh.setFocusable(false);
        btnHocSinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocSinh.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnHocSinh.setMinimumSize(new java.awt.Dimension(105, 65));
        btnHocSinh.setPreferredSize(new java.awt.Dimension(105, 65));
        btnHocSinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocSinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHocSinh);
        jToolBar1.add(jSeparator9);

        btnCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Address book.png"))); // NOI18N
        btnCauHoi.setText("Quản Lý Đề");
        btnCauHoi.setFocusable(false);
        btnCauHoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCauHoi.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnCauHoi.setMinimumSize(new java.awt.Dimension(105, 65));
        btnCauHoi.setPreferredSize(new java.awt.Dimension(105, 65));
        btnCauHoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCauHoiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCauHoi);
        jToolBar1.add(jSeparator7);

        btnDiemTongHop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Bar chart.png"))); // NOI18N
        btnDiemTongHop.setText("Thống Kê Câu Hỏi");
        btnDiemTongHop.setFocusable(false);
        btnDiemTongHop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiemTongHop.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnDiemTongHop.setMinimumSize(new java.awt.Dimension(105, 65));
        btnDiemTongHop.setPreferredSize(new java.awt.Dimension(105, 65));
        btnDiemTongHop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDiemTongHop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemTongHopActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDiemTongHop);
        jToolBar1.add(jSeparator5);

        btnDangXuatGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Log out.png"))); // NOI18N
        btnDangXuatGV.setText("Đăng xuất");
        btnDangXuatGV.setFocusable(false);
        btnDangXuatGV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuatGV.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnDangXuatGV.setMinimumSize(new java.awt.Dimension(105, 65));
        btnDangXuatGV.setPreferredSize(new java.awt.Dimension(105, 65));
        btnDangXuatGV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuatGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatGVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuatGV);
        jToolBar1.add(jSeparator6);

        btnThoat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Stop.png"))); // NOI18N
        btnThoat2.setText("Thoát");
        btnThoat2.setFocusable(false);
        btnThoat2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat2.setMaximumSize(new java.awt.Dimension(123123, 60));
        btnThoat2.setMinimumSize(new java.awt.Dimension(105, 65));
        btnThoat2.setPreferredSize(new java.awt.Dimension(105, 65));
        btnThoat2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThoat2);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Info.png"))); // NOI18N
        jLabel22.setText("Hệ thống quản lý thi");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Alarm.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hocsinhLayout = new javax.swing.GroupLayout(hocsinh);
        hocsinh.setLayout(hocsinhLayout);
        hocsinhLayout.setHorizontalGroup(
            hocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hocsinhLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(179, 179, 179))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hocsinhLayout.setVerticalGroup(
            hocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hocsinhLayout.createSequentialGroup()
                .addGroup(hocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hocsinhLayout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(hocsinhLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab.addTab("Giáo viên", hocsinh);

        jDesktopPane2.setLayer(tab, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        mnuHeThong.setText("Hệ thống");

        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Log out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator1);
        mnuHeThong.add(jSeparator2);

        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Stop.png"))); // NOI18N
        mniThoat.setText("Thoát ứng dụng");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");

        mniQLiHocSinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Conference.png"))); // NOI18N
        mniQLiHocSinh.setText("Học sinh");
        mniQLiHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLiHocSinhActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLiHocSinh);
        mnuQuanLy.add(jSeparator14);

        mniQLiCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Address book.png"))); // NOI18N
        mniQLiCauHoi.setText("Câu hỏi");
        mniQLiCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLiCauHoiActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLiCauHoi);
        mnuQuanLy.add(jSeparator15);

        mniQLiGiaoVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Clien list.png"))); // NOI18N
        mniQLiGiaoVien.setText("Giáo viên");
        mniQLiGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLiGiaoVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLiGiaoVien);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");

        mniTKNguoiThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/User group.png"))); // NOI18N
        mniTKNguoiThi.setText("Người thi");
        mniTKNguoiThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKNguoiThiActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKNguoiThi);

        mniTKBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Certificate.png"))); // NOI18N
        mniTKBangDiem.setText("Bảng điểm");
        mniTKBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKBangDiemActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKBangDiem);

        mniTKDiemTongHop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Bar chart.png"))); // NOI18N
        mniTKDiemTongHop.setText("Câu Hỏi");
        mniTKDiemTongHop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKDiemTongHopActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKDiemTongHop);

        jMenuBar1.add(mnuThongKe);

        mnuTroGiup.setText("Trợ giúp");

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Brick house.png"))); // NOI18N
        mniGioiThieu.setText("Giới Thiệu Phần Mềm");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatGVActionPerformed
        // TODO add your handling code here:
        logoff();
    }//GEN-LAST:event_btnDangXuatGVActionPerformed

    private void btnCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCauHoiActionPerformed
        // TODO add your handling code here:
        openQLCauHoi();
    }//GEN-LAST:event_btnCauHoiActionPerformed

    private void btnLBTheoMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLBTheoMonActionPerformed
        // TODO add your handling code here:
        btn(true);
    }//GEN-LAST:event_btnLBTheoMonActionPerformed

    private void btnDiemTongHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemTongHopActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_btnDiemTongHopActionPerformed

    private void btnHocSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocSinhActionPerformed
        // TODO add your handling code here:
        openQLHocSinh();
    }//GEN-LAST:event_btnHocSinhActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnKetQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetQuaActionPerformed
        // TODO add your handling code here:
        openKetQua();
    }//GEN-LAST:event_btnKetQuaActionPerformed

    private void mniQLiHocSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLiHocSinhActionPerformed
        // TODO add your handling code here:
        openQLHocSinh();
    }//GEN-LAST:event_mniQLiHocSinhActionPerformed

    private void mniQLiCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLiCauHoiActionPerformed
        // TODO add your handling code here:
        openQLCauHoi();
    }//GEN-LAST:event_mniQLiCauHoiActionPerformed

    private void mniQLiGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLiGiaoVienActionPerformed
        // TODO add your handling code here:
        GiaoVienJFrame gv = new GiaoVienJFrame();
        jDesktopPane2.add(gv);
        gv.setVisible(true);
    }//GEN-LAST:event_mniQLiGiaoVienActionPerformed

    private void btnThoat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat2ActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btnThoat2ActionPerformed

    private void mniTKNguoiThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKNguoiThiActionPerformed
        // TODO add your handling code here:
        openThongKe(0);
    }//GEN-LAST:event_mniTKNguoiThiActionPerformed

    private void mniTKBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKBangDiemActionPerformed
        // TODO add your handling code here:
        openThongKe(1);
    }//GEN-LAST:event_mniTKBangDiemActionPerformed

    private void mniTKDiemTongHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKDiemTongHopActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_mniTKDiemTongHopActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        logoff();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnLBTongHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLBTongHopActionPerformed
        // TODO add your handling code here:
        ExamJFrame ef;
        try {
            ef = new ExamJFrame("TH");
            fc(ef,false);
            btn(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở exam");
        }
    }//GEN-LAST:event_btnLBTongHopActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        // TODO add your handling code here:
        openGioiThieu();
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void btnToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToanActionPerformed
        // TODO add your handling code here:
        ExamJFrame ef;
        try {
            ef = new ExamJFrame("M01");
            fc(ef,false);
            btn(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở exam");
        }
    }//GEN-LAST:event_btnToanActionPerformed

    private void btnLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLyActionPerformed
        // TODO add your handling code here:
        ExamJFrame ef;
        try {
            ef = new ExamJFrame("M02");
            fc(ef,false);
            btn(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở exam");
        }
    }//GEN-LAST:event_btnLyActionPerformed

    private void btnHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaActionPerformed
        // TODO add your handling code here:
        ExamJFrame ef;
        try {
            ef = new ExamJFrame("M03");
            fc(ef,false);
            btn(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở exam");
        }
    }//GEN-LAST:event_btnHoaActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        logoff();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    public void fc(JInternalFrame fc,boolean b){
        fc.setResizable(b);
        fc.setClosable(b);
        fc.setMaximizable(b);
        fc.setIconifiable(b);
        jDesktopPane2.add(fc);
        fc.setVisible(true);
        fc.setLocation((jDesktopPane2.getWidth() - fc.getWidth())/2,(jDesktopPane2.getHeight()-fc.getHeight())/2);
    }
    
    public void btn(boolean b){
        btnToan.setVisible(b);
        btnLy.setVisible(b);
        btnHoa.setVisible(b);
    }
    public void exit() {
        if (DialogHelper.confirm(this, "Bạn thực sự muốn kết thúc?")) {
            System.exit(0);
        }
    }
    
    public void openGioiThieu() {
         new GioiThieuJDialog(this, true).setVisible(true); 
    }

    public void openKetQua() {
        KetQuaJFrame kq = new KetQuaJFrame();
        fc(kq,true);
    }

    public void openQLCauHoi() {
        CauHoiJFrame ch = new CauHoiJFrame();
        fc(ch,true);
    }

    public void openThongKe(int index) {
        ThongKeJFrame tk = new ThongKeJFrame(index);
        fc(tk,true);
    }

    public void openQLHocSinh() {
        QLHocSinhJFrame qlhs = new QLHocSinhJFrame();
        fc(qlhs,true);
    }

    public void logoff() {
        ShareHelper.logoff();
        this.dispose();
        this.openLogin();
    }

    public void openLogin() {
        MainJFrame dk = new MainJFrame();
        dk.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCauHoi;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDangXuatGV;
    private javax.swing.JButton btnDiemTongHop;
    private javax.swing.JButton btnHoa;
    private javax.swing.JButton btnHocSinh;
    private javax.swing.JButton btnKetQua;
    private javax.swing.JButton btnLBTheoMon;
    private javax.swing.JButton btnLBTongHop;
    private javax.swing.JButton btnLy;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat2;
    private javax.swing.JButton btnToan;
    private javax.swing.JPanel hocsinh;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMhs;
    private javax.swing.JLabel lblTen;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniQLiCauHoi;
    private javax.swing.JMenuItem mniQLiGiaoVien;
    private javax.swing.JMenuItem mniQLiHocSinh;
    private javax.swing.JMenuItem mniTKBangDiem;
    private javax.swing.JMenuItem mniTKDiemTongHop;
    private javax.swing.JMenuItem mniTKNguoiThi;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
